SELECT description
FROM course;

SELECT description, cost
FROM course;

SELECT * FROM course;

SELECT last_name, zip
FROM instructor;



SELECT DISTINCT zip
FROM instructor;

SET FEEDBACK 1;

--- 2.2--
SELECT FIRST_NAME , LAST_NAME from student;
SELECT  city , state , zip  FROM ZIPCODE;
SELECT * FROM grade_type;

--FORMATING  YOUR RESULTS
COL description FORMAT  A13
COL created_by FORMAT A8
COL modified_by FORMAT A8

--FORMATING NUMBER
COL cost FORMAT $ 9,999.99
COL cost FORMAT $9,999.99
SELECT  DISTINCT  cost FROM COURSE;
SELECT  DISTINCT  cost FROM COURSE;

SELECT LETTER_GRADE FROM GRADE_CONVERSION;

--2.2.2
SELECT  letter_grade
FROM grade_conversion;

SELECT DISTINCT letter_grade
FROM grade_conversion;


SET FEEDBACK 1;
SELECT  DISTINCT  cost FROM course;

--ERROR
SELECT  DISTINCT  COURSE_NO FROM class;


---2.3
SELECT COURSE_NO FROM COURSE;

--Palabras que se refieren al buffer de lasconsulatas antetiores
sql> LIST
sql> 1
sql> CHANGE/course_no/description

SELECT * FROM COURSE;
SELECT  state FROM ZIPCODE;

--EXCEUTE FILE SQL
SQL>@c:\exmaple\myfile2

SELECT EMPLOYER FROM STUDENT;
SELECT salutation , FIRST_NAME, LAST_NAME , phone FROM INSTRUCTOR;
SELECT  DISTINCT  state FROM  ZIPCODE;

--2.3.1 Answers
SELECT EMPLOYER FROM STUDENT;
SQL> C/SELECT/SELECT phone,
SELECT phone , REGISTRATION_DATE FROM  STUDENT;

SQL> L

----- 2.3.2
SELECT  SALUTATION , FIRST_NAME , LAST_NAME , PHONE FROM INSTRUCTOR;
SQL>@file.sql
SELECT DISTINCT  state FROM ZIPCODE;
SELECT  DISTINCT  ZIP FROM  ZIPCODE;

/* MULTI COMMENT*/
-- COMMENT LINE


---2.4 WHERE CLAUSE : COMPARASION AND LOGICAL OPERARTORS
SELECT  FIRST_NAME , LAST_NAME , PHONE  FROM
INSTRUCTOR WHERE LAST_NAME= 'Schorin';

DESCR INSTRUCTOR;

--NO ROWS
SELECT FIRST_NAME , LAST_NAME , PHONE FROM INSTRUCTOR
WHERE LAST_NAME='schorin';

--NOT EQUALS
SELECT  FIRST_NAME , LAST_NAME , PHONE FROM INSTRUCTOR
WHERE LAST_NAME <> 'Schorin';

SELECT  DESCRIPTION , cost FROM COURSE WHERE COST>=1195;


---BETWEEN COMPARISON OPERATOR
SELECT  DESCRIPTION , COST FROM COURSE WHERE COST
BETWEEN  1000 AND 1100;

---IN OPERATOR THE IN OPERATOR WORKS WITH OF LIST OF VALUES , SEPARATED BY COMMAS
-- conatined within a set of patehesese
-- NO LISTA VALORES EN ESE RANGO DE PRECIOS
SELECT  DESCRIPTION , COST  FROM COURSE
WHERE  COST IN (1095 , 1595);


--LIKE OPERATOR
SELECT FIRST_NAME ,  LAST_NAME , PHONE   FROM INSTRUCTOR
WHERE LAST_NAME LIKE 'S%';

--%
SELECT FIRST_NAME , LAST_NAME FROM INSTRUCTOR WHERE LAST_NAME LIKE  '_o%';

-- NEGATING USING NOT
SELECT LAST_NAME ,PHONE FROM INSTRUCTOR WHERE LAST_NAME NOT LIKE 'S%';
