REM primero consultemos desde SYS
REM primero consultemos desde SYS
REM primero consultemos desde SYS
REM primero consultemos desde SYS
REM primero consultemos desde SYS

desc dba_tablespaces
select tablespace_name, initial_extent,
	max_extents,max_size
	from dba_tablespaces;
	
REM ELIMINEMOS LOS TABLESPACES
DROP TABLESPACE TBS_ESIME
   INCLUDING CONTENTS AND DATAFILES;
   
DROP TABLESPACE TBS_ESCOM
   INCLUDING CONTENTS AND DATAFILES;
   
DROP TABLESPACE TBS_ESIAT
   INCLUDING CONTENTS AND DATAFILES;
   
DROP TABLESPACE TBS_ESIAZ
   INCLUDING CONTENTS AND DATAFILES;
   

set pagesize 99
set linesize 130
set colsep '|=|'
set feedback on
 SET NULL 'NADA'
 
REM PROPUESTA UTILIZAR UNA SEQUENCIA PARA LAS MATRICULAS


drop sequence id_alumno_sq;
create sequence id_alumno_sq 
	increment by 1
	start with 1000
	minvalue 1000
	maxvalue 1000000;

select id_alumno_sq.NEXTVAL from dual;	
select id_alumno_sq.CURRVAL from dual;

----------------------------
REM PARA UTLIZAR EL MODELO QUE SIGUE PARA GENERAR DATOS}

/*

 insert into alumnos_ESIAZ 
 select id_alumno_sq.NEXTVAL,'ESIAZ',SYSDATE
	FROM DUAL CONNECT BY LEVEL < 20;

*/



REM  CONSULTAR LOS DIRECTORIOS 
REM 
select * from dba_directories;
desc dba_directories
column owner format a10
column directory_name format a25
column directory_path format a65
select owner, directory_name, directory_path
	from dba_directories;
	
REM CONSULTAR LOS TABLESPACE
	
desc dba_tablespaces
select tablespace_name, initial_extent,
	max_extents,max_size
	from dba_tablespaces;
REM
REM  CREAR LOS TABLESPACES CON USUARIO SYS
REM 
CREATE TABLESPACE TBS_ESIME
	DATAFILE 'C:\Users\ORA_bases\ALUMNOS_ESIME.BDF'
	SIZE 2G;
CREATE TABLESPACE TBS_ESCOM
	DATAFILE 'C:\Users\ORA_bases\ALUMNOS_ESCOM.BDF'
	SIZE 2G;
CREATE TABLESPACE TBS_ESIAT
	DATAFILE 'C:\Users\ORA_bases\ALUMNOS_ESIAT.BDF'
	SIZE 2G;
CREATE TABLESPACE TBS_ESIAZ
	DATAFILE 'C:\Users\ORA_bases\ALUMNOS_ESIAZ.BDF'
	SIZE 2G;	
REM CONSULTAR LOS TABLESPACES 

select tablespace_name, initial_extent,
	max_extents,max_size/1024/1024 MEGAS
	from dba_tablespaces;
	
REM GENERAR UNA TABLA GLOBAL GENERALIZADA CON PARTICIONES 
REM  SE REQUIERE LA EDICION ENTREPRISE
	
	
DROP  TABLE ALUMNOS_IPN;
CREATE TABLE ALUMNOS_IPN
 (ID_ALUMNO NUMBER(10),
 ESCUELA VARCHAR2(6),
 FECHA DATE DEFAULT SYSDATE) 
 PARTITION BY LIST(ESCUELA) 
	(PARTITION ESIME VALUES('ESIME') TABLESPACE TBS_ESIME,
	 PARTITION ESCOM VALUES('ESCOM') TABLESPACE TBS_ESCOM,
	 PARTITION ESIAT VALUES('ESIAT') TABLESPACE TBS_ESIAT,
	 PARTITION ESIAZ VALUES('ESIAZ') TABLESPACE TBS_ESIAZ);
	 
 REM SI TUVIERAMOS HABILITADA LA OPCION  EXPRESS EDITION
 REM EJECUTARLO EN ENTERPRISE EDITION 
 REM   POR LO TANTO 
 --            
 REM LO EJECUTAREMOS EN TABLAS REGULARES INDIVIDUALES
 REM CREATNDO UNA TABLA PARA CADA ESCUELA.
 REM   ALUMNOS DE    ESIME
 DROP  TABLE ALUMNOS_ESIME;
CREATE TABLE ALUMNOS_ESIME
 (ID_ALUMNO NUMBER(10),
 ESCUELA VARCHAR2(6),
 FECHA DATE DEFAULT SYSDATE) TABLESPACE TBS_ESIME;
 
 insert into alumnos_ESIME 
 select level,'ESIME',SYSDATE
	FROM DUAL CONNECT BY LEVEL < 20;
	
 insert into alumnos_ESIME 
 select id_alumno_sq.NEXTVAL,'ESIME',SYSDATE
	FROM DUAL CONNECT BY LEVEL < 20;
	
SELECT * FROM ALUMNOS_ESIME;
--------------------------------------------
 REM   ALUMNOS DE    ESCOM 
 DROP  TABLE ALUMNOS_ESCOM;
CREATE TABLE ALUMNOS_ESCOM 
 (ID_ALUMNO NUMBER(10),
 ESCUELA VARCHAR2(6),
 FECHA DATE DEFAULT SYSDATE) TABLESPACE TBS_ESCOM;
 
 insert into alumnos_ESCOM 
 select id_alumno_sq.NEXTVAL,'ESCOM',SYSDATE
	FROM DUAL CONNECT BY LEVEL < 20;

SELECT * FROM ALUMNOS_ESCOM;

-- -----------------------------------------------
 REM   ALUMNOS DE    ESIAT 
 DROP  TABLE ALUMNOS_ESIAT;
CREATE TABLE ALUMNOS_ESIAT 
 (ID_ALUMNO NUMBER(10),
 ESCUELA VARCHAR2(6),
 FECHA DATE DEFAULT SYSDATE) TABLESPACE TBS_ESIAT;
 
 insert into alumnos_ESIAT 
 select id_alumno_sq.NEXTVAL,'ESIAT',SYSDATE
	FROM DUAL CONNECT BY LEVEL < 20;

SELECT * FROM ALUMNOS_ESIAT;

--   -----------------------------------------------
 REM   ALUMNOS DE    ESIAZ 
 DROP  TABLE ALUMNOS_ESIAZ;
CREATE TABLE ALUMNOS_ESIAZ 
 (ID_ALUMNO NUMBER(10),
 ESCUELA VARCHAR2(6),
 FECHA DATE DEFAULT SYSDATE) TABLESPACE TBS_ESIAZ;
 
 insert into alumnos_ESIAZ 
 select id_alumno_sq.NEXTVAL,'ESIAZ',SYSDATE
	FROM DUAL CONNECT BY LEVEL < 20;

SELECT * FROM ALUMNOS_ESIAZ;

-- --------------------------------

REM CIFRAS DE CONTROL 

SELECT COUNT(*) FROM ALUMNOS_ESIME;
SELECT COUNT(*) FROM ALUMNOS_ESCOM;
SELECT COUNT(*) FROM ALUMNOS_ESIAT;
SELECT COUNT(*) FROM ALUMNOS_ESIAZ;

REM ULTIMA MATRICULA GENERADA 

SELECT 'ULTIMA MATRICULA ',id_alumno_sq.CURRVAL FROM DUAL;





SELECT COUNT(*) FROM ALUMNOS_ESIAZ;

REM
REM  AHORA CONSULTEMOS LAS TABLAS DEL DICCIONARIO DE DATOS
REM 
	
REM CONNECTADO COMO    sys
REM CONNECTADO COMO    sys
REM CONNECTADO COMO    sys
REM CONNECTADO COMO    sys
REM CONNECTADO COMO    sys


SELECT OWNER,TABLE_NAME, TABLESPACE_NAME,
	NUM_ROWS 
	FROM DBA_TABLES
	WHERE OWNER = 'SERGIONAVA';
	
SELECT OWNER,TABLE_NAME, TABLESPACE_NAME,
	NUM_ROWS 
	FROM DBA_TABLES
	WHERE OWNER = 'SERGIOMOSQL';
	
SELECT OWNER,TABLE_NAME, TABLESPACE_NAME,
	NUM_ROWS, IOT_NAME 
	FROM DBA_TABLES
	WHERE OWNER = 'SERGIONAVA'
	AND TABLE_NAME 
	 IN ('ALUMNOS_ESCOM','ALUMNOS_ESIAT','ALUMNOS_ESIAZ','ALUMNOS_ESIME');
	 
 select tablespace_name, initial_extent,NEXT_EXTENT,
	max_extents,max_size/1024/1024 MEGAS
	from dba_tablespaces;
	
select table_name from dict
where table_name like '%TABLESPACE%';


select table_name from dict
where table_name like '%SEQUEN%';