---RESULT: John T.,T.,John
SELECT  FIRST_NAME , SUBSTR(FIRST_NAME , INSTR(FIRST_NAME, '.')-1) mi,
       SUBSTR(FIRST_NAME ,1, INSTR(FIRST_NAME , '.')-2) FIRST
FROM STUDENT WHERE  INSTR(FIRST_NAME , '.')>=3;