select * from nls_session_parameters;
ALTER SESSION SET NLS_LANGUAGE= 'AMERICAN' NLS_TERRITORY= 'AMERICA' NLS_CURRENCY= '$' NLS_ISO_CURRENCY= 'AMERICA' NLS_NUMERIC_CHARACTERS= '.,' NLS_CALENDAR= 'GREGORIAN' NLS_DATE_FORMAT= 'DD-MON-RR' NLS_DATE_LANGUAGE= 'AMERICAN' NLS_SORT= 'BINARY'

ALTER SESSION 'DD-MON-YYYY HH24:MI:SS'
alter system set NLS_DATE_FORMAT='DD/MON/RRRR' scope = both
alter session set NLS_DATE_FORMAT='DD/MON/RRRR';

ALTER SESSION SET NLS_LANGUAGE=ENGLISH;